version: "3.9"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'hockey'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '127.0.0.1:3366:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  ts:
    depends_on:
      - db
    image: node:slim
    restart: always
    ports:
      - '8061:8080'
    expose:
      - '8061'
    volumes:
      - .:/app:rw
    command:
      - /bin/bash
      - "-c" 
      - "cd /app; node dist/backend/src/index.js"
volumes:
  my-db: 
